#server:
#  tomcat:
#    uri-encoding: UTF-8
#    max-threads: 1000
#    min-spare-threads: 30
#  port: 5168
#spring:
#  profiles:
#    #加载额外组件配置，可配置多个，以","分隔
#    include: db,log
#  datasource:
#    # 数据库地址
#    url: jdbc:mysql://192.168.10.192:3306/openfire2?useSSL=false
#    # 账号
#    username: openfire2
#    # 密码
#    password: openfire2